version: "3.8"

services:
  web:
    env_file: .env
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    expose:
      - 3000
    ports:
      - 3000:3000