application:
  port: 8080
  
database:
  username: "dev"
  password: "dev"
  port: 5112
  host: "localhost"
  db_name: "repo"
  require_ssl: false

redis:
  uri: "<your_redis_uri>"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60